name: Deploy Databricks

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      resource_group_location:
        required: true
        type: string
      databricks-host:
        required: true
        type: string
    secrets:
      pat:
        required: true
      azure_credentials:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "abi-databricks-${{ inputs.env_name }}"

    env:
      ResourceGroupName: "ABI-Databricks-GitHub-${{ inputs.env_name }}"
      ResourceGroupLocation: ${{ inputs.resource_group_location }}

    steps:
      - name: Download iac files
        uses: actions/download-artifact@v3
        with:
          name: iac_artifacts
          path: iac/

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Create resource group if not exists
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"

      - name: Deploy ARM resources
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: iac/databricks.json

      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0

      - name: Download src files
        uses: actions/download-artifact@v3
        with:
          name: src_artifacts
          path: src/

      - name: databricks-import-directory
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          # Databricks host
          databricks-host: ${{ inputs.databricks-host }}
          # Databricks token
          databricks-token: ${{ secrets.pat }}
          # LOCAL_NOTEBOOKS_PATH
          local-path: src/
          # REMOTE_NOTEBOOK_PATH
          remote-path: /
